=== skilja95/XMLWS/Firma/schemas/NalogZaPrenos.xsd
<?xml version="1.0" encoding="UTF-8"?>
<xs:schema xmlns:xs="http://www.w3.org/2001/XMLSchema" elementFormDefault="qualified"
    targetNamespace="http://www.ftn.uns.ac.rs/nalogZaPrenos"
    xmlns:upl="http://www.ftn.uns.ac.rs/nalogZaPrenos" xmlns:gl="http://www.ftn.uns.ac.rs/xmlws">
    <xs:element name="nalog_za_prenos">
        <xs:complexType>
            <xs:sequence>
                <xs:element name="id_poruke" type="upl:TIDPoruke"> </xs:element>
                <xs:element name="duznik">
                    <xs:simpleType>
                        <xs:restriction base="xs:string">
                            <xs:maxLength value="255"/>
                        </xs:restriction>
                    </xs:simpleType>
                </xs:element>
                <xs:element name="svrha_placanja">
                    <xs:simpleType>
                        <xs:restriction base="xs:string">
                            <xs:maxLength value="255"/>
                        </xs:restriction>
                    </xs:simpleType>
                </xs:element>
                <xs:element name="primalac">
                    <xs:simpleType>
                        <xs:restriction base="xs:string">
                            <xs:maxLength value="255"/>
                        </xs:restriction>
                    </xs:simpleType>
                </xs:element>
                <xs:element name="podaci_o_uplati">
                    <xs:complexType>
                        <xs:sequence>
                            <xs:element name="oznaka_valute" type="upl:TOznaka_valute"> </xs:element>
                            <xs:element name="iznos" type="upl:TIznos"> </xs:element>
                            <xs:element name="racun_duznika" type="upl:TRacun"/>
                            <xs:element name="racun_poverioca" type="upl:TRacun"/>
                            <xs:element name="datum_valute" type="xs:date"/>
                            <xs:element minOccurs="1" name="hitno" type="xs:boolean" default="true"
                                nillable="false"/>
                            <xs:element name="datum_naloga" type="xs:date"/>
                        </xs:sequence>
                    </xs:complexType>
                </xs:element>
            </xs:sequence>
        </xs:complexType>
    </xs:element>
    <xs:simpleType name="TBrojRacuna">
        <xs:restriction base="xs:string">
            <xs:pattern value="\d{3}-\d{13}-\d{2}"/>
        </xs:restriction>
    </xs:simpleType>
    <xs:complexType abstract="false" name="TRacun">
        <xs:sequence>
            <xs:element name="broj_racuna">
                <xs:simpleType>
                    <xs:restriction base="upl:TBrojRacuna"/>
                </xs:simpleType>
            </xs:element>
            <xs:element name="broj_modela">
                <xs:simpleType>
                    <xs:restriction base="xs:integer">
                        <xs:totalDigits value="2"/>
                    </xs:restriction>
                </xs:simpleType>
            </xs:element>
            <xs:element name="poziv_na_broj">
                <xs:simpleType>
                    <xs:restriction base="xs:string">
                        <xs:maxLength value="20"/>
                    </xs:restriction>
                </xs:simpleType>
            </xs:element>
        </xs:sequence>
    </xs:complexType>
    <xs:simpleType name="TIDPoruke">
        <xs:restriction base="xs:string">
            <xs:maxLength value="50"/>
            <xs:minLength value="1"/>
        </xs:restriction>
    </xs:simpleType>
    <xs:simpleType name="TPIB">
        <xs:restriction base="xs:string">
            <xs:length value="11"/>
        </xs:restriction>
    </xs:simpleType>
    <xs:simpleType name="TSWIFT">
        <xs:restriction base="xs:string">
            <xs:length value="8"/>
            <xs:pattern value="[A-Z]{6}[A-Z1-9]{2}"/>
        </xs:restriction>
    </xs:simpleType>
    <xs:simpleType name="TAdresa">
        <xs:restriction base="xs:string">
            <xs:maxLength value="255"/>
        </xs:restriction>
    </xs:simpleType>
    <xs:simpleType name="TOznaka_valute">
        <xs:restriction base="xs:string">
            <xs:length value="3"/>
        </xs:restriction>
    </xs:simpleType>
    <xs:simpleType name="TIznos">
        <xs:restriction base="xs:decimal">
            <xs:totalDigits value="15"/>
            <xs:fractionDigits value="2"/>
        </xs:restriction>
    </xs:simpleType>
</xs:schema>

=== skilja95/XMLWS/Firma/xmlovi/NalogZaPrenos3.xml
<?xml version="1.0" encoding="UTF-8"?>
<nalog_za_prenos xmlns="http://www.ftn.uns.ac.rs/nalogZaPrenos"
    xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
    xsi:schemaLocation="http://www.ftn.uns.ac.rs/nalogZaPrenos file:/C:/Users/skilj/Desktop/Firma/schemas/NalogZaPrenos.xsd">
    <id_poruke>c3</id_poruke>
    <duznik>M1</duznik>
    <svrha_placanja>RTGS</svrha_placanja>
    <primalac>M4</primalac>
    <podaci_o_uplati>
        <oznaka_valute>RSD</oznaka_valute>
        <iznos>300500</iznos>
        <racun_duznika>
            <broj_racuna xmlns="http://www.ftn.uns.ac.rs/xmlws">000-0000000000000-01</broj_racuna>
            <broj_modela xmlns="http://www.ftn.uns.ac.rs/xmlws">18</broj_modela>
            <poziv_na_broj xmlns="http://www.ftn.uns.ac.rs/xmlws">189</poziv_na_broj>
        </racun_duznika>
        <racun_poverioca>
            <broj_racuna xmlns="http://www.ftn.uns.ac.rs/xmlws">000-0000000000000-04</broj_racuna>
            <broj_modela xmlns="http://www.ftn.uns.ac.rs/xmlws">11</broj_modela>
            <poziv_na_broj xmlns="http://www.ftn.uns.ac.rs/xmlws">189</poziv_na_broj>
        </racun_poverioca>
        <datum_valute>2017-06-27</datum_valute>
        <hitno>0</hitno>
        <datum_naloga>2017-06-27</datum_naloga>
    </podaci_o_uplati>
</nalog_za_prenos>
